version: "3"

services:

  frontend:
    image: frontend-dev
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend-dev
    expose:
      - "80"
    volumes:
      # Bind code
      - "../frontend:/app"
      # Use image node_modules
      - "/app/node_modules"
    environment:
      # Fix hot reloading
      - CHOKIDAR_USEPOLLING=true
    networks:
      - webnet

  backend:
    image: backend-dev
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend-dev
    expose:
      - "80"
    volumes:
      - "../backend:/app"
    networks: 
      - webnet