version: "3"

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend-dev
    ports:
      - "8080:8080"
    volumes:
      # Bind code
      - "../frontend:/app"
      # Use image node_modules
      - "/app/node_modules"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - webnet