version: "3"

services:

  nginx: 
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet

  database:
    image: postgres:latest
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: thingsandstuff
      POSTGRES_DB: postgres
    deploy:
      placement:
        constraints: [node.role == manager]
    networks: 
      - webnet

networks:
  webnet: